// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxrcqEQMRlJvtN_Yd8H6jE2N18MaSWRJU',
    appId: '1:374403579665:web:3e51b91b25cabeda1516b0',
    messagingSenderId: '374403579665',
    projectId: 'encuestor',
    authDomain: 'encuestor.firebaseapp.com',
    storageBucket: 'encuestor.firebasestorage.app',
    measurementId: 'G-YETG40LY6E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAC295Dhv2Krz0eflTBT7yGtmjKKmNsKaI',
    appId: '1:374403579665:android:bc21e7326b7324281516b0',
    messagingSenderId: '374403579665',
    projectId: 'encuestor',
    storageBucket: 'encuestor.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxrcqEQMRlJvtN_Yd8H6jE2N18MaSWRJU',
    appId: '1:374403579665:web:d29935bbb7cb75d71516b0',
    messagingSenderId: '374403579665',
    projectId: 'encuestor',
    authDomain: 'encuestor.firebaseapp.com',
    storageBucket: 'encuestor.firebasestorage.app',
    measurementId: 'G-TJK3R8N97L',
  );

}